services:
  environment:
    - TOGETHER_API_KEY=${TOGETHER_API_KEY}
    - ANYSCALE_API_KEY=${ANYSCALE_API_KEY}
    - CONFIDENT_API_KEY=${CONFIDENT_API_KEY}
  ollama-container:
    image: ollama/ollama
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434
  streamlit-app:
    image: flaskapi:latest
    ports:
      - 8501:8501
