version: '3'
services:
  ollama-container:
    image: ollama/ollama
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434
  streamlit-app:
    image: flaskapi:latest
    ports:
      - 8501:8501
  api:
    build: .
    container_name: app
    command: /bin/sh -c "/app/start.sh"
    expose:
      - "5001"
